openapi: 3.1.0
info:
  version: v1
  title: 建立(訂閱)一個 webhook
  summary: 由 外聯 端 建立 (訂閱) 一個 webhook
  description: "# 說明\r\n接收 Webhook 的 URL（Endpoint）規範\r\n1. 立即回應 200 OK\r\n    - 當收到 Webhook 時，必須立即回應 HTTP 狀態碼 200 OK，以告知 digiwin_DSP 平台事件已成功接收，避免重複傳送。\r\n2. 回應時機建議\r\n    - 建議在收到 Webhook 請求後，立即回應，不要等到完成內部處理後才回應。\r\n    - 可將接收到的請求儲存至佇列（Queue）後，立即回應 200 OK，並在後續處理請求內容。\r\n3. 通知回應規範\r\n    - 回應時間：必須在 30 秒內以 HTTPS 回應 HTTP 狀態碼 200 OK。\r\n    - 正確回應：確保回覆正確的 HTTP 狀態碼 200，避免回應失敗。\r\n4. 回應失敗影響\r\n   -  如果 digiwin_DSP 平台在傳送事件至 Webhook 時，未能在幾秒內收到任何回應，將會：\r\n        - 若多次傳送仍失敗，平台可能封鎖該 Webhook 伺服器或採取其他措施。\r\n        - 這可能影響外聯的應用服務正常運作，還請留意。\r\n\r\n# 共通性JSON\r\n- 事件觸發時DSP所發出的JSON一律包含以下外框\r\n```json\r\n{\r\n    \"digi_header\": {\r\n        \"digi_host\": {\r\n            \"prod\": \"DSP\",\r\n            \"ip\": \"\",\r\n            \"timestamp\": \"\"\r\n        },\r\n        \"digi_service\": {\r\n            \"prod\": \"\",\r\n            \"name\": \"\"\r\n        }\r\n    },\r\n    \"digi_body\": {\r\n        \"std_data\": {\r\n            \"parameter\": {\r\n                \"request\": \"{JSON}\"\r\n            }\r\n        }\r\n    }\r\n}\r\n```\r\n\r\n# 庫存數量更新\r\n- product/inventory_update\r\n```json\r\n{\r\n    \"prod\": \"EC001\",\r\n    \"platform_id\": \"123456\",\r\n    \"sale_page_id\": \"abc123\",\r\n    \"spec_list\": [\r\n        {\r\n            \"spec_id\": \"abc123001\",\r\n            \"product_no\": \"A001_1\",\r\n            \"update_mode\":\"total\",\r\n            \"stock\": 10,\r\n            \"preorder_stock\": 15\r\n        }\r\n    ]\r\n}\r\n```\r\n\r\n|節點|說明|\r\n|:--|:----|\r\n|prod|外部系統代號，鼎新DSP使用可忽略|\r\n|platform_id|平台唯一識別碼(店號)|\r\n|sale_page_id|商品頁ID|\r\n|spec_list|規格陣列|\r\n|spec_id|平台品號(平台規格ID)|\r\n|product_no|ERP品號|\r\n|update_mode|異動類型，total:總量; adjust:異動量<br> `註：ERP端標準只提供總量更新，異動量更新須進行個案客製才有作用。`|\r\n|stock|庫存量(integer)，當udpate_mode為adjust時，此為庫存異動量(可為正負數)；反之，此為庫存總量(即此節點預設為庫存總量)|\r\n|preorder_stock|預購可售量(integer)，若為null 不更新，反之則更新預購可售量|\r\n\r\n# 倉儲貨態更新\r\n- wms/logistics/package/update\r\n```json\r\n{\r\n    \"form_no\": \"TM231002W00072\",\r\n    \"func_name\": \"erp.wms.arrived\",\r\n    \"status_date\": \"2023/08/30\",\r\n    \"status_time\": \"12:00:00\",\r\n    \"tracking_number\": \"1002-6790-1101\",\r\n    \"distributor_code\": \"HCT\",\r\n    \"message\": \"訊息\"\r\n}\r\n```\r\n |節點|說明|\r\n|:--|:----|\r\n|form_no|訂單編號|\r\n|func_name|資料分類|\r\n|status_date|狀態日期|\r\n|status_time|狀態時間|\r\n|tracking_number|託運單號|\r\n|distributor_code|配送商代碼，HCT:新竹倉儲; CAT:統一速達;|\r\n|message|訊息| \r\n# 發票資料更新\r\n- invoice/update\r\n```json\r\n[\r\n    {\r\n        \"platform_id\": \"41142\",\r\n        \"digi_form_no\": \"2113||20240617001\",\r\n        \"form_no\": \"TG20240617001\",\r\n        \"invoice_type\": \"1\",\r\n        \"invoice_date\": \"2024-04-03\",\r\n        \"invoice_time\": \"00:00:00\",\r\n        \"invoice_number\": \"EV54838339\",\r\n        \"buyer_gid\": \"28682266\",\r\n        \"random_code\": \"0000\",\r\n        \"invoice_address\": \"賣方營業人地址\",\r\n        \"invoice_title\": \"賣方名稱\",\r\n        \"invoice_status\": \"1\",\r\n        \"carrier_code\": \"3J0002\",\r\n        \"carrier_showid\": \"/XCCYDHQ\",\r\n        \"carrier_hiddenid\": \"/XCCYDHQ\",\r\n        \"love_code\": \"12345678\"\r\n    }\r\n]\r\n```\r\n\r\n|節點|說明|\r\n|:--|:----|\r\n|platform_id|店號|\r\n|digi_form_no|鼎新內部單號|\r\n|form_no|訂單編號|\r\n|invoice_type|發票類型， 1:二聯式; 2:三聯式; 3:二聯式收銀機發票; 4:三聯式收銀機發票; 5:電子計算機發票; 6:免用統一發票; 7:電子發票; A:增值稅專用發票; B:普通發票; C:免用發票|\r\n|invoice_date|發票日期，格式:yyyy-MM-dd|\r\n|invoice_time|發票時間，格式:HH:mm:ss|\r\n|invoice_number|發票號碼|\r\n|buyer_gid|買方統一編號|\r\n|random_code|隨機碼|\r\n|invoice_address|發票地址|\r\n|invoice_title|發票抬頭|\r\n|invoice_status|發票狀態， 1:開立; 2:作廢; 3:折讓; 4:註銷; 5:折讓作廢|\r\n|carrier_code|載具類別，1H0001:一卡通; 1K0001:悠遊卡; 2G0001:iCash; 3J0002:手機條碼; CQ0001:自然人憑證|\r\n|carrier_showid|顯碼|\r\n|carrier_hiddenid|隱碼|\r\n|love_code|捐贈碼|"

servers:
  - url: 'https://digiwindsp.digiwin.com/DSP/api/webhook'
    description: 正式區
  - url: 'https://digiwindsp.digiwin.com/DSP_UAT/api/webhook'
    description: 測試區
paths:
  /v1/webhook:
    post:
      summary: 註冊WEBHOOK
      description: 由 外聯 端 建立 (訂閱) 一個 webhook
      operationId: webhook
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                digi_header:
                  type: object
                  properties:
                    digi_host:
                      type: object
                      properties:
                        prod:
                          type: string
                          description: 呼叫方代碼
                        ip:
                          type: string
                          description: 呼叫方IP
                        timestamp:
                          type: string
                          description: 呼叫方時間戳記
                    digi_service:
                      type: object
                      properties:
                        prod:
                          type: string
                          description: 服務方代碼
                        name:
                          type: string
                          description: 服務名稱
                digi_body:
                  type: object
                  properties:
                    std_data:
                      type: object
                      properties:
                        parameter:
                          type: object
                          properties:
                            request:
                              type: object
                              properties:
                                prod:
                                  type: string
                                  description: |-
                                    外部平台代碼

                                    |代碼|說明|
                                    |--|:--|
                                    |OFFICIALWEBSITE|自有官網|
                                    |QUICKPER|自有官網V2|
                                platform_id:
                                  type: string
                                  description: |-
                                    外部平台識別碼(店號)<br>
                                    請求 DSP 查詢的平台
                                action:
                                  type: string
                                  description: |-
                                    訂閱內容
                                    
                                    |action代號|action名稱|
                                    |:-:|:-:|
                                    |product/inventory_update|庫存數量更新|
                                    |wms/logistics/package/update|倉儲貨態更新|
                                    |invoice/update|發票資料更新|
                                address:
                                  type: string
                                  description: "webhook call back URL<br>接收webhook 的URL"
                                  maxLength: 500
                              required:
                                - prod
                                - platform_id
                                - action
                                - address
            examples:
              Request 範例:
                value:
                  digi_header:
                    digi_host:
                      prod: OFFICIALWEBSITE
                      ip: xxx.xxx.xxx.xxx
                      timestamp: '20161018132542116'
                    digi_service:
                      prod: DSP
                      name: webhook
                  digi_body:
                    std_data:
                      parameter:
                        request:
                          prod: 'OFFICIALWEBSITE'
                          platform_id: '41142'
                          action: product/inventory_update
                          address: 'http://officialwebsite/webhook'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  srvver:
                    type: string
                  std_data:
                    type: object
                    properties:
                      execution:
                        type: object
                        properties:
                          code:
                            type: string
                          description:
                            type: string
                      response:
                        type: object
                        properties:
                          platform_id:
                            type: string
                            description: 平台識別碼
                          address:
                            type: string
                            description: |-
                              webhook call back URL<br>
                              接收webhook 的URL
                          action:
                            type: string
                x-examples:
                  Example 1:
                    srvver: '1.0'
                    std_data:
                      execution:
                        code: '0'
                        description: ''
                      response:
                        total_point: 200
                        expire_date: '2022-06-08 09:00:00'
                        redeem_point_profile:
                          - point: 10
                            amount: 1
                            using_min_price: 0
              examples:
                成功:
                  value:
                    srvver: '1.0'
                    std_data:
                      execution:
                        code: '0'
                        description: ''
                      response:
                        platform_id: xxxxxxxx
                        address: 'http://officialwebsite/webhook'
                        action: product/inventory_update
                失敗:
                  value:
                    srvver: '1.0'
                    std_data:
                      execution:
                        code: '-1'
                        description: '系統異常:資料庫存取異常'
      security:
        - ApiKeyAuth: []
      servers:
        - url: 'https://digiwindsp.digiwin.com/DSP/api/webhook'
          description: 正式區
        - url: 'https://digiwindsp.digiwin.com/DSP_UAT/api/webhook'
          description: 測試區
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      description: 由鼎新 DSP 提供 API KEY
      name: DSP-api-key
      in: header
security:
  - ApiKeyAuth: []
x-internal: false
